name: build

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  windows:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'CMake: Configure'
        run: cmake -B build -A Win32

      - name: 'CMake: Build'
        run: cmake --build build --config Release

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/xiloader/Release/xiloader.exe
